--DROP TABLE IF EXISTS user;
--
--CREATE TABLE IF NOT EXISTS users(
--id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
--username VARCHAR(50) NOT NULL ,
--password VARCHAR(500) NOT NULL,
--created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
--updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
--);

--DROP TABLE IF EXISTS inventory;
--
--CREATE TABLE IF NOT EXISTS inventory(
--inventory_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
--report_date DATE NOT NULL,
--product_id VARCHAR(100) NOT NULL,
--quantity FLOAT NOT NULL,
--created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
--updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
--);

DROP TABLE IF EXISTS product;

CREATE TABLE IF NOT EXISTS product(
product_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
name VARCHAR(100) NOT NULL
);